apiVersion: v1  
kind: Pod # object of type
metadata:  
  name: client-pod
  labels: 
    component: web
spec:
  containers:   # this pod will run this container
    - name: client  # to reference / logging / networking
      image: rcamposs/multi-worker  # image from dockerhub 
      ports: 
        - containerPort: 9999  # on this container , expose port <> outside
